name: Build Xamarin.Android app

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set default Xamarin SDK versions
      run: |
        ls '/Library/Frameworks/Xamarin.Android.framework/Versions'
        ls '/Library/Frameworks/Mono.framework/Versions'
        $VM_ASSETS/select-xamarin-sdk-v2.sh --android=11

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore /src/ForgetMeNot.sln

    - name: Build
      run: msbuild /src/ForgetMeNot.sln /t:PackageForAndroid /p:Configuration=Debug