name: Build Xamarin.Android app

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=11.0

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore src/ForgetMeNot.sln

    - name: Build
      run: msbuild src/ForgetMeNot.sln /t:ForgetMeNot_Droid:Build /p:Configuration=Debug